#!/bin/bash
#./listerine - a companion to the google gargle project
#relies on googlegrape, aria2c, curl, and youtube-dl

SERVER=199.48.254.90:8081
GARGLE=./googlegargle

while getopts :u: OPT; do
    case $OPT in
	u)
	    USERNAME="$OPTARG"
	    ;;
	*)
	    echo "usage: `basename $0` [-u USERNAME]"
            exit 1;
    esac
done

warning() {
  echo "$0: $*" >&2
}

error() {
  echo "$0: $*" >&2
  exit 2
}

if [ -z $USERNAME ]; then
    error "You must supply a username with the -u option before you can begin"
fi

if [ ! -f $GARGLE ]; then
    error "Couldn't find googlegargle. Are you sure you cloned everything from the git repository?"
fi

EXTERN_IP=`curl --silent ipv4.icanhazip.com` #Do not change without good reason, or underscor will eat your brains

askserver() {
    cmd="$1"
    shift
    rest=
    for chunk in "$@"; do
        rest="$rest/$chunk"
    done
    if ! curl --silent --fail "http://$SERVER/$cmd/${USERNAME}$rest"; then
        error "Couldn't contact the listerine server. The listerine server could be down, or your network."
    fi
}

askserver introduce $EXTERN_IP

while true; do
  echo "Getting an id from $SERVER, authenticated as $USERNAME with IP $EXTERN_IP"
  id=`askserver getID | sed "s/[^0-9\\-]//g"`
  if [ -z $id ]; then
    error "The server didn't give us an id. This could mean the server is broken, or possibly that we're finished."
  fi

  echo ID is $id
  $GARGLE -- "$id"

  SEPDIB=$(echo "$id" | sed 's/-//g' | cut -c1)
  SECDIB=$(echo "$id" | sed 's/-//g' | cut -c2)
  THIRDIB=$(echo "$id" | sed 's/-//g' | cut -c3)
  file="$SEPDIB/$SECDIB/$THIRDIB/$id/$id.flv"
  if [ -f $file ]; then
    hash=`sha1sum "$file"|awk '{print $1}'`
    size=`du -b "$file"|awk '{print $1}'`
    echo "Hash is $hash"
    echo "ID is $id"
    echo "USERNAME is $USERNAME"
    echo "Size is $size"
    askserver finishVid $id $size $hash
  else
    warning "Failed to download anything for $id."
  fi
  if [ -f STOP ]; then 
    echo "$0: I see a file called STOP. Stopping."
    exit 0
  fi
done
