#!/bin/bash
#./listerine - a companion to the google gargle project
#relies on googlegrape, aria2c, curl, and youtube-dl

# Change the username below to something unique to you. ALPHANUMERIC ONLY!
USERNAME=
SERVER=199.48.254.90:8081
GARGLE=./googlegargle

warning() {
  echo "$0: $*" >&2
}

error() {
  echo "$0: $*" >&2
  exit 1
}

if [ -z $USERNAME ]; then
    error "You must edit the listerine script and add a username before you can begin"
fi

if [ ! -f $GARGLE ]; then
    error "Couldn't find googlegargle. Are you sure you cloned everything from the git repository?"
fi

EXTERN_IP=`curl --silent ipv4.icanhazip.com` #Do not change without good reason, or underscor will eat your brains

askserver() {
  rest="$@" | tr " " "/"
  curl --silent "http://$SERVER/$1/$USERNAME/$rest"
  if [ $? ]; then
    error "Couldn't contact the listerine server. Is your network down?"
  fi
}

askserver introduce $EXTERN_IP

while true; do
  echo "Getting an id from $SERVER, authenticated as $USERNAME with IP $EXTERN_IP"
  id=`askserver getID | sed "s/[^0-9\\-]//g"`
  if [ -z $id ]; then
    error "The server didn't give us an id. This could mean the server is broken, or possibly that we're finished."
  fi

  echo ID is $id
  $GARGLE -- "$id"

  SEPDIB=$(echo "$id" | sed 's/-//g' | cut -c1)
  SECDIB=$(echo "$id" | sed 's/-//g' | cut -c2)
  THIRDIB=$(echo "$id" | sed 's/-//g' | cut -c3)
  file="$SEPDIB/$SECDIB/$THIRDIB/$id/$id.flv"
  if [ -f $file ]; then
    hash=`$file"|awk '{print $1}'`
    size=`du -b "$file"|awk '{print $1}'`
    echo "Hash is $hash"
    echo "ID is $id"
    echo "USERNAME is $USERNAME"
    echo "Size is $size"
    askserver finishVid $id $size $hash
  else
    warning "Failed to download anything for $id."
  fi
  if [ -f STOP ]; then 
    echo "$0: I see a file called STOP. Stopping."
    exit 0
  fi
done
